### ISSUE TITLE
Connection to server has broken in last commit 

### ISSUE THREAD

**Issue by TheGITofTeo997** [TheGITofTeo997/PokeProject#2]
On 24/01/2019 we tried to implement some structure changes to both server and client in order to make them work and communicate with the server correctly, this was done in commit (9fdc5d8). Apparently, these kind of changes broke something in the socket connection between the server and the client (actually we still don't know what or who to blame for this issue). I would personally suggest to proceed as written below:

- Since we don't know what caused the issue, we could blame the LAN we were working in for that. Maybe the day of that commit something wasn't working correctly and inbound/outbound traffic related to the server was getting blocked in that LAN.
- Maybe there was something wrong with Hamachi or with the VPN itself. Please note that some connections were working, but not as usual. We eventually got to estabilish some connections but they were broken and/or not working as expected.
- The last option we could think of, which is probably the worst one, is that there's some problem within the code and we messed up something with this last commit. In such case we would need to investigate what caused the problem and hopefully fix that, eventually we will close this issue.

If the problem laid in the LAN connection we were using we could consider this issue already closed, but in order to do that we need to be sure that **outside** of that LAN, all is working correctly and we need to test that. If this is the case, we need to open another issue related to that LAN problem, since we need to get the project working in **that** LAN.

**Comment by Drunper** [comment]
I did some test in local and i came to the same conclusion. So i started to resolve the other issues with the code and, as i went on, more issues emerged. Many blasphemies later, i resolved almost everything but, since i've not committed the various hotfixes that i made (i made a single large commit), i created a second branch in which i pushed all the changes. If it works then we could declare this and other issue solved and merge the connection_fix branch to the master one.
![screenshot 83](https://user-images.githubusercontent.com/37589213/51753050-2bf49a80-20b9-11e9-9a57-1a09f68309f2.png)
![screenshot 86](https://user-images.githubusercontent.com/37589213/51753051-2bf49a80-20b9-11e9-9558-a2300bce29af.png)

**Comment by TheGITofTeo997** [comment]
We will go on with some tests on 29/01/2019 in our working LAN. If we get the project to work correctly we will merge the new branch with the old one and consider both this and #3 closed. 

In the case we will encounter some connection issues we will need to open a new issue that will state all the problems we get in our working LAN.

**Comment by TheGITofTeo997** [comment]
There was a problem in the working LAN, now the connection is working.
