### ISSUE TITLE
IP control on the client side

### ISSUE THREAD

**Issue by Drunper** [TheGITofTeo997/PokeProject#23]
As it stands now we don't have a control for the IP address on the client side. If the user is a stupid one we could encounter a lot of problems. The implementation of a control could greatly improve the solidity of our application.

**Comment by TheGITofTeo997** [comment]
Issue has been widely fixed in last commit (afbe73c), However we still need to move the actionListener for this button that does this check and we actually still need to make use of this method, @Drunper will use this in the connection process. Just remember that the method is available.

We can consider this issue closed.
