### ISSUE TITLE
Background is not repainting correctly with Pokemon transparent GIFs

### ISSUE THREAD

**Issue by TheGITofTeo997** [TheGITofTeo997/PokeProject#7]
Because GIFs are animated and transparent, background does not repaint correctly and becames dirty with every frame, we need to find a workaround for this.

**Comment by TheGITofTeo997** [comment]
Maybe we can find this useful: https://stackoverflow.com/questions/26330550/java-gif-animation-not-repainting-correctly

**Comment by Drunper** [comment]
This issue is caused
![bulbasaur 2](https://user-images.githubusercontent.com/37589213/52086676-d41dce00-25a7-11e9-89fe-51a2aef284a9.gif)
 by the gif we use, not by our code. Probably, the gifs we are using at the moment use as a disposal method the "restore to previous" instead of "restore to background color". Changing this with code will require a lot of effort and time that, sadly, we don't have. The solution i found is changing the gif, as i show with my attachment. Further tests needed.

**Comment by TheGITofTeo997** [comment]
I am going to rebuild the JAR with the new GIF that has been provided and i will repack all. Then, I'm going to test if this kind of GIF is going to work.

**Comment by TheGITofTeo997** [comment]
This new type of GIF is now working so we can close this issue, but please note that we still have to find the back sprites to match this type.
